// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function handleClick(_event) {
  console.log("testclicked");
  return /* () */0;
}

function Component1(Props) {
  var message = Props.message;
  return React.createElement("div", {
              onClick: handleClick
            }, message);
}

var make = Component1;

export {
  handleClick ,
  make ,
  
}
/* react Not a pure module */
